#!/usr/bin/python
# -*- coding: utf-8 -*-

dict_cyrillic = {
    'dict_sharp_flat': {'dict_sharp_dur_moll': {'ls_dur_sharp': (
                                                                 'До',
                                                                 'До#',
                                                                 'Ре',
                                                                 None,
                                                                 'Ми',
                                                                 'Фа',
                                                                 'Фа#',
                                                                 'Соль',
                                                                 None,
                                                                 'Ля',
                                                                 None,
                                                                 'Си',
                                                                 ),
                                                'ls_moll_sharp': (
                                                                  'до',
                                                                  'до#',
                                                                  'ре',
                                                                  'ре#',
                                                                  'ми',
                                                                  'фа',
                                                                  'фа#',
                                                                  'Соль',
                                                                  'Соль#',
                                                                  'ля',
                                                                  'ля#',
                                                                  'си',
                                                                  ),
                                                },
                        'dict_flat_dur_moll': {'ls_dur_flat': (
                                                               'До',
                                                               'Реb',
                                                               'Ре',
                                                               'Миb',
                                                               'Ми',
                                                               'Фа',
                                                               'Сольb',
                                                               'Соль',
                                                               'Ляb',
                                                               'Ля',
                                                               'Сиb',
                                                               'Си',
                                                               ),
                                               'ls_moll_flat': (
                                                                'до',
                                                                None,
                                                                'ре',
                                                                'миb',
                                                                'ми',
                                                                'фа',
                                                                None,
                                                                'соль',
                                                                'ляb',
                                                                'ля',
                                                                'сиb',
                                                                'си',
                                                                ),
                                               }, },
                }

dict_lat = {
    'dict_sharp_flat': {'dict_sharp_dur_moll': {'ls_dur_sharp': (
                                                                 'C',
                                                                 'Cis',
                                                                 'D',
                                                                 None,
                                                                 'E',
                                                                 'F',
                                                                 'Fis',
                                                                 'G',
                                                                 None,
                                                                 'A',
                                                                 None,
                                                                 'B',
                                                                 ),
                                                'ls_moll_sharp': (
                                                                  'c',
                                                                  'cis',
                                                                  'd',
                                                                  'dis',
                                                                  'e',
                                                                  'f',
                                                                  'fis',
                                                                  'g',
                                                                  'gis',
                                                                  'a',
                                                                  'ais',
                                                                  'h'
                                                                  ),
                                                },
                        'dict_flat_dur_moll': {'ls_dur_flat': (
                                                               'C',
                                                               'Des',
                                                               'D',
                                                               'Es',
                                                               'E',
                                                               'F',
                                                               'Ges',
                                                               'G',
                                                               'As',
                                                               'A',
                                                               'B',
                                                               'H',
                                                               ),
                                               'ls_moll_flat': (
                                                                 'c',
                                                                 None,
                                                                 'd',
                                                                 'es',
                                                                 'e',
                                                                 'f',
                                                                 None,
                                                                 'g',
                                                                 'as',
                                                                 'a',
                                                                 'b',
                                                                 'h',
                                                                 ),
                                               }, },
                }

dict_pitch_classes = {
    'dict_sharp_flat': {'dict_sharp_dur_moll': {'ls_dur_sharp': (
                                                                 'C',
                                                                 'C#',
                                                                 'D',
                                                                 None,
                                                                 'E',
                                                                 'F',
                                                                 'F#',
                                                                 'G',
                                                                 None,
                                                                 'A',
                                                                 None,
                                                                 'B'
                                                                 ),
                                                'ls_moll_sharp': (
                                                                  'c',
                                                                  'c#',
                                                                  'd',
                                                                  'd#',
                                                                  'e',
                                                                  'f',
                                                                  'f#',
                                                                  'g',
                                                                  'g#',
                                                                  'a',
                                                                  'a#',
                                                                  'h'),

                                                },
                        'dict_flat_dur_moll': {'ls_dur_flat': (
                                                               'C',
                                                               'Db',
                                                               'D',
                                                               'Eb',
                                                               'E',
                                                               'F',
                                                               'Gb',
                                                               'G',
                                                               'Ab',
                                                               'A',
                                                               'B',
                                                               'H'
                                                               ),
                                               'ls_moll_flat': (
                                                                'c',
                                                                None,
                                                                'd',
                                                                'eb',
                                                                'e',
                                                                'f',
                                                                None,
                                                                'g',
                                                                'ab',
                                                                'a',
                                                                'b',
                                                                'h'
                                                                ),

                                               }, },
                }

dict_camelot = {
    'dict_sharp_flat': {'dict_sharp_dur_moll': {'ls_dur_sharp': (
                                                                 '8B',
                                                                 '3B',
                                                                 '10B',
                                                                 None,
                                                                 '12B',
                                                                 '7B',
                                                                 '2B',
                                                                 '9B',
                                                                 None,
                                                                 '11B',
                                                                 None,
                                                                 '1B',
                                                                 ),
                                                'ls_moll_sharp': (
                                                                  '5A',
                                                                  '12A',
                                                                  '7A',
                                                                  '2A',
                                                                  '9A',
                                                                  '4A',
                                                                  '11A',
                                                                  '6A',
                                                                  '1A',
                                                                  '8A',
                                                                  '3A',
                                                                  '10A',
                                                                  ),
                                                },
                        'dict_flat_dur_moll': {'ls_dur_flat': (
                                                               '8B',
                                                               '3B',
                                                               '10B',
                                                               '5B',
                                                               '12B',
                                                               '7B',
                                                               '2B',
                                                               '9B',
                                                               '4B',
                                                               '11B',
                                                               '6B',
                                                               '1B',
                                                               ),
                                               'ls_moll_flat': (
                                                                '5A',
                                                                None,
                                                                '7A',
                                                                '2A',
                                                                '9A',
                                                                '4A',
                                                                None,
                                                                '6A',
                                                                '1A',
                                                                '8A',
                                                                '3A',
                                                                '10A',
                                                                ),
                                               }, },
                }

tup_dicts_with_notes = (
    dict_cyrillic,
    dict_lat,
    dict_pitch_classes,
    dict_camelot,
    )

tup_names_of_notation = (
    'Кириллица',
    'Латиница',
    'Программный тип записи',
    'Колесо Камелота',
    )
